server:
  port: 8888
dubbo:
  application:
    name: project-web
  consumer:
    timeout: 120000
  protocol:
    name: dubbo
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper

spring:
  application:
      name: project-web
  session:
    store-type: redis
    timeout: 1800s

  redis:
    host: localhost
    # Redis服务器连接端口
    port: 6379
    password: redis
    #默认是索引为0的数据库
    database: 0
    # 连接超时时间（毫秒）
    timeout: 5000ms
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100000ms
        # 连接池中的空闲连接
        max-idle: 10
        min-idle: 0

  mail:
#    host: smtp.qq.com
    host: smtp.163.com
    username: 18806719815@163.com
    password: qwer1234
    port: 465
    default-encoding: utf-8
#    protocol: smtp
    properties:
#      mail.debug: true
      mail.smtp.auth: true
      mail.smtp.timeout: 25000
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: false
      mail.smtp.socketFactory.fallback: false
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory

  servlet:
    # 上传文件大小限制，默认1M
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

exception:
  mail:
    to: 1274462659@qq.com,syf1274462659@163.com